### ISSUE TITLE
Incremental search / search as you type

### ISSUE THREAD

**Issue by drrlvn** [Wilfred/deadgrep#13]
Updating the results as the user types would make the UI more responsive and would greatly improve usability.

Maybe even immediately show the results for the words under point, that would make deadgrep feel much snappier.

**Comment by Wilfred** [comment]
I'm open to exploring this, but if you want incremental searching, you probably want `ivy-rg`. I use it sometimes :)

Deadgrep is intentionally organised around results buffers. This has a number of advantages:

* It works much better for large repositories, where you don't want to restart a slow search on every keypress.
* It doesn't use the minibuffer, so you can easily have multiple results buffers to compare.
* You can keep the results buffer and refer back to it, only updating when you press `g`. I use this for API updating.

However, it might be interesting to immediately start searching whilst we read the search term from the minibuffer. Most searches are fast. This would work better for text searches than for regexps, as an unfinished regexp is often syntactically broken.

**Comment by NightMachinary** [comment]
@Wilfred What's the link of `ivy-rg`? Google can't find it. Is it the same as `+ivy/project-search-from-cwd`?
For interactive search; Can't you provide a read-only mode that reads the input on the buffer to actually construct the query string instead of editing the buffer? Then together with the refresh command which can be assigned to `RET`, things would be good. We can also provide a timer that automatically refreshes every 0.2 seconds if the query has changed.

**Comment by To1ne** [comment]
There's also `consult-ripgrep` for user of [consult](https://github.com/minad/consult).
