### ISSUE TITLE
open results buffer in other window

### ISSUE THREAD

**Issue by wbolster** [Wilfred/deadgrep#49]
thanks for this package, it seems to have quite a few nice features (i was using `ag.el`) but one thing that bothers me a lot is that the results buffer is displayed in the _current_ window. i often use search to find context for code that i'm working on, and that code now disappears from the screen as soon as i search. `ag.el` opens in another window (another ‘column’ on my screen typically) and i can keep looking at the code from which i started my search.

it seems changing this is not possible. or is it?

**Comment by wbolster** [comment]
changing `(switch-to-buffer)` to `(switch-to-buffer-other-window)` seems to do the right thing for me, but changing one hard-coded behaviour with another doesn't seem the right approach. ;)

**Comment by Wilfred** [comment]
Have you tried `deadgrep-visit-result-other-window`, which is bound to `o`?

**Comment by wbolster** [comment]
i am aware of that command, but it's for jumping to results. i want the deadgrep buffer itself to open elsewhere.

sorry if i was not clear.

**Comment by eugeneia** [comment]
I think using `switch-to-buffer-other-window` and `find-file-other-window` by default is the right choice, since they respect the `pop-up-frames` variable and do the expected thing for folks who configured it. If the current default behaviour of clobbering windows is desired, maybe put it behind a configuration flag?

FWIW, I am not saying the current behaviour is bad, I just think using the mentioned default makes `deadgrep` behave more intuitive and predicable in within the broader Emacs ecosystem (i.e., as in expecting a replacement for `rgrep`.)

**Comment by thomasf** [comment]
yeah, popwin seems to be unable to control the deadgrep window , I guess it's because what @eugeneia says.

**Comment by Wilfred** [comment]
OK, I think we have consensus on changing the logic to `switch-to-buffer-other-window`. Both seem natural to me, and the reasons you mention (popwin, pop-up-frames) seem sufficiently compelling to change default behaviour.

I've rolled the version number: I tagged the previous commit as 0.8, and added a note in CHANGELOG.md about this change in 0.9. If this breaks anyone's workflow, let me know.

**Comment by wbolster** [comment]
thanks, @wilfred. i guess this could even be made customizable since people seem to have different preferences.
