### ISSUE TITLE
Maybe collapse all files with a command? (Magit-style)

### ISSUE THREAD

**Issue by Whil-** [Wilfred/deadgrep#68]
This is a feature request/suggestion.

It would be cool if there was a command that could be used to collapse all files, as currently can be done with tab for individual files.

Maybe use the same convension as Magit does? Since there only are two states and no hierarchy Alt-1 could be used for "all hidden" and Alt-2 for "all visible"

WDYT?

**Comment by Wilfred** [comment]
Have you tried imenu? `M-x imenu` in a results buffer will give you an overview.

I think this feature would still be useful though.

**Comment by Whil-** [comment]
Have not tried that. Will do now. Thanks for the suggestion.

**Comment by elkarouh** [comment]
Hello,
First, many thanks for this wonderful tool !!!

In fact, I have the same need. 
I have lots of results from many different files and the i-menu work-around doesn't work for me because the file path is very long and it gets truncated by imenu.
So having a way to collapse all headers with a key stroke sould be a life-saver.
